version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.12.29
    steps:
      - checkout
      - run:
          command: terraform fmt -check -recursive -diff
      - run:
          working_directory: examples/test
          command: terraform init
      - run:
          working_directory: examples/test
          command: terraform validate
